tasks:
  initial_search_task:
    context: "Initial threat intelligence gathering phase"
    description: |
      Search for the latest cybersecurity threats related to: {initial_query}
      Use only the following sources: {sources}
      Gather basic information about the threat, including its name, type, and a brief description.
      Compile a list of relevant URLs for further investigation.
    expected_output: |
      A structured report containing:
      1. Basic information about the identified threat(s) related to the query
      2. A list of relevant URLs for further investigation
      3. Any initial observations or patterns noticed during the search
    agent: osint_analyst

  data_extraction_task:
    context: "Detailed threat data extraction phase"
    description: |
      Using the information and URLs provided by the OSINT Analyst, extract comprehensive threat data.
      Focus on gathering all relevant information as per the EmergingThreat model.
    expected_output: |
      A structured dataset containing:
      1. Detailed threat descriptions
      2. Indicators of Compromise (IoCs): IP addresses, domains, URLs, file hashes, email addresses
      3. Tactics, Techniques, and Procedures (TTPs)
      4. Associated threat actors and their known aliases
      5. Connected campaigns
      6. Targeted sectors and countries
      7. Exploited CVEs
      8. First seen and last seen dates
      9. Data sources and references
      10. Any additional relevant metadata
    agent: data_scraper

  validation_task:
    context: "Threat intelligence validation and enrichment phase"
    description: |
      Thoroughly validate and verify the threat intelligence gathered by the Data Scraper.
      Use the NLP Tool to process and analyze the data for consistency and completeness.
      Enrich the data with additional context and confidence scores.
    expected_output: |
      A validated and enriched threat intelligence report containing:
      1. Verified information for each identified threat component
      2. Confidence scores for each data point
      3. Any corrections or adjustments made during validation
      4. Flagged inconsistencies or potential false positives
      5. Additional context or insights derived from the NLP analysis
      6. A list of any information that could not be verified, with explanations
    agent: validation_agent

  graph_creation_task:
    context: "Knowledge graph creation and updating phase"
    description: |
      Create a new knowledge graph in Neo4j based on the validated threat intelligence.
      Ensure the graph structure adheres to the EmergingThreat model.
      Use the Graph Update Tool to create all necessary nodes and relationships.
    expected_output: |
      1. Confirmation of a new knowledge graph created in Neo4j
      2. A summary of the graph structure, including:
         - Total number of nodes created (by type)
         - Total number of relationships created (by type)
         - Any potential anomalies or issues encountered during creation
      3. The graph ID and instructions on how to query the new graph in Neo4j Browser
      4. A list of any data that could not be incorporated into the graph, with explanations
    agent: knowledge_graph_agent

  summary_task:
    context: "Final threat intelligence summary generation"
    description: |
      Create a comprehensive summary report of the newly discovered and graphed threat intelligence.
      Highlight key findings, potential impacts, and recommended actions.
      Include references to the created Neo4j graph for further exploration.
    expected_output: |
      A comprehensive report containing:
      1. Executive summary of key findings
      2. Detailed breakdown of the identified threat(s)
      3. Potential impacts on various sectors or systems
      4. Recommended mitigation strategies and actions
      5. References to the Neo4j graph, including sample queries for exploration
      6. Any gaps in the intelligence or areas requiring further investigation
    agent: knowledge_graph_agent