tasks:
  - name: "SearchTask"
    description: >
      Search the web for information on cybersecurity threats based on user queries and provide a list of URLs.
    expected_output: >
      A list of URLs containing relevant information about cybersecurity threats.
    inputs:
      - name: "query"
    agent: "OSINTAnalyst"

  - name: "GatheringTask"
    description: >
      Gather and scrape intelligence on cybersecurity threats from the provided URLs.
    expected_output: >
      Extracted information from the URLs, including Threat Actors, Campaigns, IoCs, and TTPs.
    inputs:
      - name: "urls"
    agent: "OSINTInformationGatheringAgent"

  - name: "ValidationTask"
    description: >
      Verify the accuracy and relevance of the intelligence gathered by the OSINT agents.
    expected_output: >
      A list of verified intelligence data, cross-referenced with the Neo4J database.
    inputs:
      - name: "intelligence"
    agent: "ValidationAgent"

  - name: "GraphUpdateTask"
    description: >
      Update the Neo4J database with new knowledge graphs based on the verified intelligence data.
    expected_output: >
      Updated knowledge graphs in the Neo4J database representing relationships between Threat Actors, Campaigns, IoCs, TTPs, and CVEs.
    inputs:
      - name: "verified_intelligence"
    agent: "KnowledgeGraphAgent"
